# Generated by Django 6.0.4 on 2026-06-02 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文件分类',
                'verbose_name_plural': '文件分类',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='文件')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[('document', '文档'), ('image', '图片'), ('spreadsheet', '表格'), ('other', '其他')], default='document', max_length=20, verbose_name='文件类型')),
                ('size', models.BigIntegerField(verbose_name='文件大小')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_analyzed', models.BooleanField(default=False, verbose_name='是否已分析')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_management.filecategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
            },
        ),
    ]
