# Generated by Django 6.0.4 on 2026-06-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='文档摘要')),
                ('extracted_info', models.JSONField(blank=True, null=True, verbose_name='提取的关键信息')),
                ('status', models.CharField(choices=[('pending', '待分析'), ('processing', '分析中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='分析状态')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_selected', models.BooleanField(default=False, verbose_name='是否为选中版本')),
            ],
            options={
                'verbose_name': 'AI分析结果',
                'verbose_name_plural': 'AI分析结果',
            },
        ),
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='操作类型')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='操作详情')),
            ],
            options={
                'verbose_name': '分析历史',
                'verbose_name_plural': '分析历史',
            },
        ),
    ]
