# Generated by Django 6.0.4 on 2026-06-02 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_analysis', '0001_initial'),
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisresult',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_management.uploadedfile', verbose_name='关联文件'),
        ),
    ]
